version: "1.0"
services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env